config/routes.rb
FrancisBlog::Application.routes.draw do
  namespace :pages do
    get "links"
    get "archive"
  end

  namespace :admin do
    get "/" => "admin#index"

    get "login" => "sessions#new"
    post "login" => "sessions#create"
    delete "logout" => "sessions#destroy"

    get "settings/stat" => "settings#stat"
    put "settings/stat" => "settings#stat_update"

    resources :attachments
    resources :entries, except: [:show]
  end

  root :to => "home#index"
  get "feed" => "home#feed"
  get "sitemap" => "home#sitemap"

  resources :entries, only: [:show]
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :file, :file_key, :user_id

  belongs_to :user

  validates :file_key, presence: true
  validates :file_key, uniqueness: { case_sensitive: false }
  validates :user, associated: true, presence: true

  def file
    @file
  end

  def file=(file)
    @file = file
  end

  def to_url
    "#{Settings.qiniu[:share_link]}/#{self.file_key}"
  end

  # 在查询之后记录原始文件
  # 为七牛远程修改文件名提供源文件名属性
  after_find do
    @origin_file_key = self.file_key
  end

  # 在更新AR之前，更新远程文件
  before_update do
    Qiniu::RS.move Settings.qiniu[:bucket_name], @origin_file_key,
                   Settings.qiniu[:bucket_name], self.file_key
  end

  # 在删除AR之前，先删除远程文件
  before_destroy do
    Qiniu::RS.delete Settings.qiniu[:bucket_name], self.file_key
  end

  # 创建之前，先上传远程文件
  # 如果上传到七牛服务器失败，则不不保存当前AR
  before_create do
    Qiniu::RS.upload_file key: self.file_key,
                          file: self.file.path,
                          uptoken: upload_token,
                          bucket: Settings.qiniu[:bucket_name]
  end

  private

  # 根据当前的空间名和时间生成上传Token
  def upload_token 
    Qiniu::RS.generate_upload_token scope: Settings.qiniu[:bucket_name]
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :content, :slug, :title, :user_id

  belongs_to :user

  validates :user, :presence => true, :associated => true
  validates :slug, :title, :content, :presence => true
  validates :slug, :uniqueness => { :case_sensitive => false }
  
  def to_html
    return "" if content.blank?
    Kramdown::Document.new(content).to_html
  end

  def to_param
    self.slug
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :site_name, :site_url

  validates :site_url, :site_name, :presence => true
  validates :site_name, :uniqueness => { :case_sensitive => false }
end

app/models/stat.rb
class Stat < RailsSettings::CachedSettings
  attr_accessible :var
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :email, :username, :password

  validates :email, :username, :presence => true
  validates :email, :username, :uniqueness => { :case_sensitive => false }

  has_many :entries, dependent: :restrict
  has_many :attachments, dependent: :restrict
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < AdministratorController
  def index
  end
end

app/controllers/admin/attachments_controller.rb
#encoding: utf-8
class Admin::AttachmentsController < AdministratorController
  def new
    @attachment = Attachment.new
  end

  def edit
    @attachment = Attachment.find params[:id]
  end

  def show
  end

  def index
    @attachments_grid = initialize_grid Attachment, include: :user, order: "created_at"
  end

  def create
    @attachment = Attachment.new params[:attachment]
    @attachment.user_id = current_user.id

    respond_to do |format|
      if @attachment.valid? and @attachment.save
        format.json { render json: @attachment }

        format.html do
          flash[:success] = "附件上传成功"
          redirect_to admin_attachments_path
        end

      else
        format.json { render json: nil }

        format.html do
          flash[:danger] = "附件上传失败，请重试"
          render "new"
        end

      end
    end
  end

  def update
    @attachment = Attachment.find params[:id]

    if @attachment.update_attributes(params[:attachment])
      flash[:success] = "文件更新成功"
      redirect_to admin_attachments_path
    else
      flash[:danger] = "文件更新失败，请重试"
      render "edit"
    end
  end

  def destroy
    @attachment = Attachment.find params[:id]

    if @attachment.destroy
      flash[:success] = "文件删除成功"
    else
      flash[:danger] = "文件删除失败，请重试"
    end

    redirect_to admin_attachments_path
  end
end

app/controllers/admin/entries_controller.rb
#encoding: utf-8
class Admin::EntriesController < AdministratorController
  def new
    @entry = Entry.new
  end

  def edit
    @entry = Entry.find_by_slug params[:id]
  end

  def index
    @entries_grid = initialize_grid(Entry,
                                    include: :user,
                                    order: "created_at",
                                    order_direction: "desc"
                                   )
  end

  def create
    @entry = current_user.entries.build params[:entry]

    if @entry.valid? and @entry.save
      flash[:success] = "创建日志成功"
      redirect_to admin_entries_path
    else
      flash.now[:danger] = "创建日志失败"
      render "new"
    end
  end

  def update
    @entry = Entry.find_by_slug params[:id]

    if @entry.update_attributes(params[:entry])
      flash[:success] = "日志更新成功"
      redirect_to admin_entries_path
    else
      flash.now[:error] = "日志更新失败"
      render "edit"
    end
  end

  def destroy
    @entry = Entry.find_by_slug params[:id]

    if @entry.destroy
      flash[:success] = "日志删除成功"
    else
      flash[:danger] = "日志删除失败"
    end

    redirect_to admin_entries_path
  end
end

app/controllers/admin/sessions_controller.rb
#encoding: utf-8
class Admin::SessionsController < AdministratorController

  layout "bootstrap-login"
  skip_before_filter :require_login, except: [:destroy]

  def new
  end

  def create
    username = params[:session][:username]
    password = params[:session][:password]

    if login(username, password)
      flash[:success] = "登录成功"
      redirect_to admin_path
    else
      flash[:danger] = "登录失败，用户名/密码错误"
      redirect_to admin_login_path
    end
  end

  def destroy
    logout
    flash[:success] = "注销成功"
    redirect_to admin_login_path
  end
end

app/controllers/admin/settings_controller.rb
#encoding: utf-8

class Admin::SettingsController < AdministratorController
  def stat
    @stat = Stat
  end

  def stat_update
    @stat = Stat
    @stat.code = params[:stat][:code]

    flash[:success] = "统计代码更新成功"
    redirect_to admin_settings_stat_path
  end
end

app/controllers/administrator_controller.rb
#encoding: utf-8

class AdministratorController < ActionController::Base
  layout "bootstrap"
  protect_from_forgery
  before_filter :require_login, expect: [:not_authenticated]

  def not_authenticated
    flash[:danger] = "需要登录授权才能访问"
    redirect_to admin_login_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "2-columns"
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def show
    @entry = Entry.find_by_slug params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def feed
    @entries = Entry.order("`created_at` DESC").limit(20)

    respond_to do |format|
      format.html
      format.xml { render content_type: "application/rss+xml" }
    end
  end

  def index
    @count = Entry.count
  end

  def sitemap
    @entry = Entry

    respond_to do |format|
      format.xml { render content_type: "application/xml" }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def links
    @links = Link.order "`site_name` ASC"
  end

  def archive
    @entries = Entry.order "`created_at` DESC"
  end
end

app/helpers/administrator_helper.rb
module AdministratorHelper
  def render_flash(items = [])
    html = ""
    items.each do |type, content|
      html << alert_template(type, content)
    end

    html.html_safe
  end

  private

  def alert_template(type, content)
    """
    <div class='alert alert-#{type.to_s} alert-dismissable'>
      <button aria-hidden='true' type='button' data-dismiss='alert' class='close'>&times;</button>
      #{content}
    </div>
    """
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_list(items=[], html = {})
    html = "<ul>"
    yield items if block_given?

    items.each do |item|
      unless current_link?(item)
        html << "<li>"
      else
        html << "<li class='active'>"
      end

      html << item << "</li>" << "\n"
    end

    html << "</ul>"
    html.html_safe
  end

  private

  def current_link?(link)
    href = link.match(/href=(['"])(.*?)(\1)/)[2] rescue all
    href and current_page?(href)
  end

end

app/views/admin/attachments/_form.html.erb
<%= form_for [:admin, attachment], html: { role: "form", class: "center-block" } do |f| %>

  <% unless flash.empty? %>
    <%= render_flash flash %>
  <% end %>

  <div class="form-group">
    <%= f.label :file_key, "文件名" %>
    <%= f.text_field :file_key, class: "form-control" %>
  </div>

  <% if attachment.new_record? %>
    <div class="form-group">
      <%= f.label :file, "选择文件" %>
      <%= f.file_field :file %>
    </div>
  <% end %>

  <% unless attachment.new_record? %>
    <div class="form-group">
      <label for="">地址</label>
      <p><%= link_to attachment.to_url, attachment.to_url %></p>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit attachment.new_record? ? "上传" : "更新", class: "btn btn-primary pull-right" %>
  </div>

<% end %>

app/views/admin/attachments/edit.html.erb
<% content_for :page_title do %>编辑附件<% end %>

<%= render partial: "form", locals: { attachment: @attachment } %>

app/views/admin/attachments/index.html.erb
<% content_for :page_title do %>附件管理<% end %>

<% unless flash.empty? %>
  <%= render_flash flash %>
<% end %>

<%= grid(@attachments_grid) do |g|

  g.column name: "#", attribute: "id" do |attachment|
    attachment.id
  end

  g.column name: "文件名", attribute: "file_key" do |attribute|
    attribute.file_key
  end

  g.column name: "作者", model: "User", attribute: "username" do |attachment|
    attachment.user.username
  end

  g.column name: "创建日期", attribute: "created_at" do |attachment|
    attachment.created_at.strftime("%Y-%m-%d %H:%m")
  end

  g.column name: "外链" do |attachment|
    link_to "链接地址", attachment.to_url
  end

  g.column do |attachment|
    link_to("编辑", edit_admin_attachment_path(attachment), class: "btn btn-default btn-xs") +
    link_to("删除", admin_attachment_path(attachment), method: :delete, class: "btn btn-danger btn-xs")
  end

end -%>

app/views/admin/attachments/new.html.erb
<% content_for :page_title do %>上传附件<% end %>

<%= render partial: "form", locals: { attachment: @attachment } %>

app/views/admin/entries/_form.html.erb
<%= form_for [:admin, entry], html: { role: "form", class: "center-block" } do |f| %>

  <% unless flash.empty? %>
    <%= render_flash flash %>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "标题" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :slug, "Slug" %>
    <%= f.text_field :slug, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content, "正文内容" %>
    <%= f.text_area :content, class: "form-control", rows: 15 %>
  </div>

  <div class="form-group">
    <%= f.submit entry.new_record? ? "添加" : "保存", class: "btn btn-primary col-xs-2 pull-right" %>
  </div>

<% end %>

app/views/admin/entries/edit.html.erb
<h3 class="form-title">编辑日志 <%= @entry.title %></h3>

<%= render :partial => "form", locals: { entry: @entry } %>

app/views/admin/entries/index.html.erb
<% content_for :page_title do %>日志管理<% end %>

<% unless flash.empty? %>
  <%= render_flash flash %>
<% end %>

<%= grid(@entries_grid) do |g|

  g.column name: "#", attribute: "id" do |entry|
    entry.id
  end

  g.column name: "Slug", attribute: "slug" do |entry|
    entry.slug
  end

  g.column name: "标题", attribute: "title" do |entry|
    entry.title
  end

  g.column name: "作者", model: "User", attribute: "username" do |entry|
    entry.user.username
  end

  g.column name: "创建日期", attribute: "created_at" do |entry|
    entry.created_at.strftime("%Y-%m-%d %H:%m")
  end

  g.column do |entry|
    link_to("编辑", edit_admin_entry_path(entry), class: "btn btn-default btn-xs") +
    link_to("删除", admin_entry_path(entry), method: :delete, class: "btn btn-danger btn-xs")
  end

end -%>

app/views/admin/entries/new.html.erb
<h3 class="form-title">添加新日志</h3>

<%= render :partial => "form", locals: { :entry => @entry } %>

app/views/admin/settings/stat.html.erb
<% content_for :page_title do %>统计代码设置<% end %>

<%= form_for @stat, url: admin_settings_stat_path, method: :put, html: { role: "form", class: "center-block" } do |f| %>

  <% unless flash.empty? %>
    <%= render_flash flash %>
  <% end %>

  <div class="form-group">
    <%= f.label "访问统计代码" %>
    <%= f.text_area :code, class: "form-control", rows: 3 %>
  </div>

  <div class="form-group">
    <%= f.submit "保存", class: "btn btn-primary col-xs-2 pull-right" %>
  </div>

<% end %>

app/views/entries/show.html.erb
<div class="entries_show">
  <div id="post_wrap">
    <div class="title"><%= @entry.title -%></div>
    <div>
      <div class="meta rt">
        <div class="username"><%= @entry.user.username -%></div>
        发表于
        <div class="datetime"><%= @entry.created_at.strftime("%Y年%m月%d日 %H:%M") -%></div>
      </div>

      <div class="clear"></div>

      <div id="mkd_wrap" class="content mkd"></div>
      <textarea id="mkd_src" class="mkd_src_wrap"><%= raw @entry.content.html_safe -%></textarea>
    </div>
  </div>
</div>

<% content_for :page_title do %><%= @entry.title %><% end %>
<% content_for :jquery_ready do %>;$("#mkd_wrap").toMarkdown({ "markdown_wrap" : "#mkd_src" });<% end %>

app/views/home/feed.html.erb
<% content_for :page_title do %>订阅本站<% end %>

<div class="home_feed">
  <h1 class="page_title">订阅本站</h1>
  <div class="page_description">感谢订阅本站RSS</div>
</div>

app/views/home/index.html.erb
<div class="home_index">
  <h1 class="page_title">欢迎页</h1>
  <div class="page_description">欢迎访问我的Blog</div>

  <div class="welcome">
    <p>因为种种原因，从第一篇日志算起，到目前目前一共有 <%= @count -%> 篇日志了，你可以在左侧的<%= link_to "归档日志", pages_archive_path %>中找到他们。</p>
    <p>这里的内容乱七八糟，也可能会包含一些令人反感的内容。所以，浏览时需谨慎。</p>
    <p>因为是我私人的Blog，所以这里的内容不确保中立性，大部分内容都带有严重的主观色彩，望见谅。</p>
    <p class="art">
    <%= link_to "http://rubyonrails.org", :class => "res_icon", :rel => "nofollow" do %>
      <%= image_tag "rails-logo.png" %>
    <% end %>
    </p>
  </div>
</div>

app/views/layouts/2-columns.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "#{yield(:page_title)} | " if content_for?(:page_title) %>Francis' Blog</title>
  <%= stylesheet_link_tag "2-columns", :media => "all" %>
  <%= javascript_include_tag "2-columns" %>
  <%= csrf_meta_tags %>
  <meta name="renderer" content="webkit|ie-stand">
  <%= auto_discovery_link_tag :rss, feed_path(format: "xml", only_path: false) %>
</head>
<body>
  <div id="container" class="pt50">
    <div class="lf sidebar">
      <div class="logo">
        <%= link_to root_path do %>
          <%= image_tag "logo.png" %>
        <% end %>
      </div>

      <div class="navigator mt25">
        <%= render_list do |item|

          item << link_to("首页", root_path)
          item << link_to("Wiki", "http://wiki.francistm.com")
          item << link_to("日志归档", pages_archive_path)
          item << link_to("友情链接", pages_links_path)

        end %>
      </div>
    </div> <!-- sidebar end -->

    <div class="content_container rt">
      <%= yield %>
    </div> <!-- content_container end -->

    <div class="clear"></div>
    <div class="stat mt20"><%= Stat.code.html_safe unless Stat.code.blank? %></div>
  </div> <!-- container end -->

  <% if content_for?(:jquery_ready) %>
    <script type="text/javascript">
      jQuery(function($) {
          <%= yield :jquery_ready %>
      });
    </script>
  <% end %>

</body>
</html>

app/views/layouts/bootstrap-login.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title><%= "#{yield :page_title} | " if content_for?(:page_title) %>Francis' Blog</title>
    <%= stylesheet_link_tag "administrator", :media => "all" %>
    <%= javascript_include_tag "administrator" %>
    <%= csrf_meta_tags %>
    <meta name="renderer" content="webkit|ie-stand">
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-xs-6 col-xs-offset-3">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title><%= "#{yield :page_title} | " if content_for?(:page_title) %>Francis' Blog</title>
    <%= stylesheet_link_tag "administrator", :media => "all" %>
    <%= javascript_include_tag "administrator" %>
    <%= csrf_meta_tags %>
    <meta name="renderer" content="webkit|ie-stand">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static" role="navigation">
      <div class="navbar-header">
        <%= link_to "Blog 后台管理", admin_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#"> 日志 <b class="caret"></b> </a>
            <ul class="dropdown-menu">
              <li><%= link_to "日志管理", admin_entries_path %></li>
              <li><%= link_to "添加新日志", new_admin_entry_path %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#"> 附件 <b class="caret"></b> </a>
            <ul class="dropdown-menu">
              <li><%= link_to "上传附件", new_admin_attachment_path %></li>
              <li><%= link_to "附件管理", admin_attachments_path %></li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 设置 <b class="caret"></b> </a>
            <ul class="dropdown-menu">
              <li><%= link_to "统计代码设置", admin_settings_stat_path %></li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.username -%><b class="caret"></b> </a>
            <ul class="dropdown-menu">
              <li><%= link_to "网站首页", root_path %></li>
              <li><%= link_to "登出", admin_logout_path, method: :delete %></li>
            </ul>
          </li>
        </ul>

      </div>

    </nav>

    <div class="container">
      <%= yield -%>
    </div>

    <div id="footer"></div>
  </body>
</html>

app/views/pages/archive.html.erb
<div class="pages_archive">
  <h1 class="page_title">日志归档</h1>
  <div class="page_description">有史以来所有的日志，按照创建时间倒序排列</div>

  <ul class="archives">
    <% @entries.each do |entry| %>

      <li class="archive_row">
        <div class="title lf"><%= link_to entry.title, entry -%></div>
        <div class="meta art rt"><%= entry.created_at.strftime "%Y年%m月%d日 %H:%M" -%></div>
        <div class="clear"></div>
      </li>

    <% end %>
  </ul>
</div>

<% content_for :page_title do %>日志归档<% end %>

app/views/pages/links.html.erb
<% content_for :page_title do %>友情链接<% end %>

<div class="pages_links">
  <h1 class="page_title">友情链接</h1>
  <div class="page_description">注：排名<em>不分</em>先后</div>

  <ul class="link_list">
    <% @links.each do |link| %>
      <li class="link_item">
        <%= link_to "#{link.site_name} - #{link.site_url}", link.site_url %>
      </li>
    <% end %>
  </ul>
</div>